spring:
  # 개발 환경용 H2 Database 설정 (파일 모드)
  datasource:
    url: jdbc:h2:file:./data/categorydb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 개발 환경용 로깅 설정
logging:
  level:
    com.musinsa.category: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
# 파일 로깅 비활성화 (콘솔에만 출력)
  # file:
  #   name: logs/musinsa-category-dev.log 